# Generated by Django 5.2.6 on 2025-10-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_passport_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='visa_history',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
