# Generated by Django 5.2.6 on 2025-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_visa_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='intro_videos/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='travel_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
